---
title: "Block groups"
author: "Satya Golla"
date: "2/7/2022"
output: html_document
---



```{r setup}
library(sf)
library(tidyverse)
```

```{r read-bg-ks}
path_name <- "./Data"
file_name <- "tl_2021_20_bg.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_bg_ks
head(all_bg_ks)
all_bg_ks                              %>%
     ggplot()                           +
      geom_sf(aes())                    +
      ggtitle("ks-bg")
```


```{r read-bg-mo}
path_name <- "./Data"
file_name <- "tl_2021_29_bg.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_bg_mo
head(all_bg_mo)
all_bg_mo                              %>%
     ggplot()                           +
      geom_sf(aes())                    +
      ggtitle("mo-bg")
```



```{r combine-bg} 
all_bg_ks                           %>%
  bind_rows(all_bg_mo)  -> mo_ks_bg 
mo_ks_bg                           %>%
 ggplot()                               +
      geom_sf(aes())                    +
      ggtitle("mo-ks-bg")  
```


```{r read-Community-Districts}
file_name <- "Community_District.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> Community_Districts
head(Community_Districts)
Community_Districts                  %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("Community_Districts")
Community_Districts %>%
  st_transform(crs=st_crs(mo_ks_bg)) -> cd
```


```{r intersect-mo-ks-bg-Community-Districts}
mo_ks_bg                      %>%
  st_intersects( cd, sparse=FALSE) -> intersect_matrix
 print(intersect_matrix)
 ggplot(data=cd, aes()) +
        geom_sf(fill="lightgreen", col="darkgreen") +
        geom_sf(data=cd[intersect_matrix, ], fill="pink", col="darkred") +
        ggtitle("mo-ks-tracts-Community-Districts")
```



```{r intersect-mo-ks-tracts-Community-Districts}
for (i in 1:2) {
  st_intersects( cd[i,], sparse=FALSE) -> intersect_matrix
  total_area  <- st_area(mo_ks_tracts[intersect_matrix,]) / 1000000
  intersect_area <- st_area(st_intersection(mo_ks_tracts[intersect_matrix,],cd[i,])) / 1000000 
  print(intersect_area)
  mo_ks_tracts[intersect_matrix,]               %>%
    ggplot(data=mo_ks_tracts[intersect_matrix,], aes())  +
      geom_sf(fill=NA, col="darkgreen")      +
      geom_sf(data = cd[i,], fill=NA, col="darkred")  -> map
  print(map)}
```