---
title: "Counties"
author: "Satya Golla"
date: "12/29/2021"
output: html_document
---

The important counties for this program are

Cass County, MO (29037)
Clay County, MO (29047)
Jackson County, MO (29095)
Johnson County, KS (20091)
Leavenworth County, KS (20103)
Miami County, KS (20121)
Wyandotte County, KS (20209)

```{r setup}
library(sf)
library(tidyverse)
```

```{r read-county}
path_name <- "./data"
file_name <- "tl_2021_us_county.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_counties
head(all_counties)
all_counties                           %>%
   filter(STATEFP==20)                    %>% 
   ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("ks-counties")
all_counties                           %>%
   filter(STATEFP==29)                    %>% 
   ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("mo-counties")
```



variable in the file 

+ Variables:
  +  "STATEFP"
  +   "COUNTYFP"
  +   "TRACTCE"
  +   "BLKGRPCE" 
  +   "AFFGEOID" 
  +   "GEOID"
  +   "NAME"
  +   "NAMELSAD"
  +   "LSAD"
  +   "ALAND"
  +   "AWATER"
  +   "geometry"
 


```{r read-johnson-county}
file_name <- "tl_2020_20091_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> johnson_county_blocks
head(johnson_county_blocks)
johnson_county_blocks                  %>%
     ggplot()                           +
      geom_sf(aes())                    +
      ggtitle("johnson_county_blocks")
```


```{r read-leavenworth-county}
file_name <- "tl_2020_20103_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> leavenworth_county_blocks
head(leavenworth_county_blocks)
leavenworth_county_blocks                         %>%
     ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("leavenworth_county_blocks")
```


```{r read-wyandotte-county}
file_name <- "tl_2020_20209_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> wyandotte_county_blocks
head(wyandotte_county_blocks)
wyandotte_county_blocks                %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("wyandotte_county_blocks")
```

```{r read-jackson-county}
file_name <- "tl_2020_29095_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> jackson_county_blocks
head(jackson_county_blocks)
jackson_county_blocks                  %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("jackson_county_blocks")
```


```{r read-cass-county}
file_name <- "tl_2020_29037_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> cass_county_blocks
head(cass_county_blocks)
cass_county_blocks                  %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("cass_county_blocks")
```


```{r read-clay-county}
file_name <- "tl_2020_29047_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> clay_county_blocks
head(clay_county_blocks)
clay_county_blocks                  %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("clay_county_blocks")
```


```{r read-miami-county}
file_name <- "tl_2020_20121_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> miami_county_blocks
head(miami_county_blocks)
miami_county_blocks                  %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("miami_county_blocks")
```



```{r combine-blocks}
johnson_county_blocks                   %>%
  bind_rows(leavenworth_county_blocks)  %>%
  bind_rows(wyandotte_county_blocks)    %>%
  bind_rows(jackson_county_blocks)      %>%
  bind_rows(cass_county_blocks)         %>%
  bind_rows(clay_county_blocks)         %>%
  bind_rows(miami_county_blocks)        %>%
   ggplot()                             +
      geom_sf(aes())                    +
      ggtitle("all_county_blocks")  
  
```



