---
title: "Neighborhoods Wyandotte County"
author: "Satya Golla"
date: "10/27/2021"
output: html_document
---
```{r setup}
library(sf)
library(tidyverse)
```

```{r read}
path_name <- "./data"
list.files(path_name)
file_name <- "Neighborhoods.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_neighborhoods
head(all_neighborhoods)


```{r built-in-tools}
all_neighborhoods                           %>%
  ggplot()                              +
  geom_sf(aes())                 +
  ggtitle("plot of all neighborhoods")


```{r union}
union_neighborhoods <- st_union(all_neighborhoods)

union_neighborhoods %>%
  ggplot() +
  geom_sf(aes()) +
  ggtitle("Union of all neighborhoods")


```{r read-leavenworth-county}
file_name <- "tl_2020_20209_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> wyandotte_county_blocks
head(wyandotte_county_blocks)
```


```{r crs}
crs_j<-st_crs(wyandotte_county_blocks)
st_crs(union_neighborhoods)<-crs_j
```

