---
title: "Neighbourhoods Johnson county"
author: "Satya Golla"
date: "10/27/2021"
output: html_document
---


```{r setup}
library(sf)
library(tidyverse)
```

```{r read}
path_name <-"./Data"
list.files(path_name)
file_name <- "Neighborhoods.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_neighborhoods
head(all_neighborhoods)
```


```{r built-in-tools}
all_neighborhoods                           %>%
  ggplot()                              +
  geom_sf(aes())                 +
  ggtitle("plot of all neighborhoods")
```


```{r union}
union_neighborhoods <- st_union(all_neighborhoods)

union_neighborhoods %>%
  ggplot() +
  geom_sf(aes()) +
  ggtitle("Union of all neighborhoods")
```


```{r read-johnson-county}
file_name <- "tl_2020_20091_tabblock10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> johnson_county_blocks
head(johnson_county_blocks)
```

```{r map-johnson-county-blocks}
johnson_county_blocks                           %>%
  ggplot()                              +
  geom_sf(aes())                 +
  ggtitle("johnson_county_blocks")
```



