---
title: "PUMAS"
author: "Satya Golla"
date: "12/30/2021"
output: html_document
---


```{r setup}
library(sf)
library(tidyverse)
```


```{r read-puma-ks}
path_name <- "./data"
file_name <- "tl_2021_20_puma10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_puma_ks
head(all_puma_ks)
all_puma_ks                           %>%
     ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("ks-puma")
```

variable in the file 

+ Variables:
  +   "STATEFP10"
  +   "PUMACE10"
  +   "GEOID10"
  +   "NAMELSAD10"
  +   "MTFCC10" 
  +   "FUNCSTAT10" 
  +   "ALAND10"
  +   "AWATER10"
  +   "INTPTLAT10"
  +   "INTPTLON10"
  +   "geometry"


```{r read-puma-mo}
path_name <- "./data"
file_name <- "tl_2021_29_puma10.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_puma_mo
head(all_puma_mo)
all_puma_mo                           %>%
     ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("mo-puma")
```


variable in the file 

+ Variables:
  +   "STATEFP10"
  +   "PUMACE10"
  +   "GEOID10"
  +   "NAMELSAD10"
  +   "MTFCC10" 
  +   "FUNCSTAT10" 
  +   "ALAND10"
  +   "AWATER10"
  +   "INTPTLAT10"
  +   "INTPTLON10"
  +   "geometry"

```{r combine-pumas}
all_puma_ks                %>%
  bind_rows(all_puma_mo)  -> mo_ks_puma 
mo_ks_puma %>%
 ggplot()                               +
      geom_sf(aes())                    +
      ggtitle("mo-ks-puma")  
```



```{r read-Community-Districts}
file_name <- "Community_District.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> Community_Districts
head(Community_Districts)
Community_Districts                  %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("Community_Districts")
Community_Districts %>%
  st_transform(crs=st_crs(mo_ks_puma)) -> cd
```




```{r intersect-puma-Community-Districts}
for(i in 1:dim(cd)[1]) {
mo_ks_puma                             %>%
st_intersects( cd[i,], sparse=FALSE) -> intersect_matrix
 map_position <- st_centroid(mo_ks_puma[intersect_matrix, ])
 ggplot(data=mo_ks_puma[intersect_matrix, ], aes()) +
        geom_sf(fill="lightgreen", col="darkgreen") +
        geom_sf(data=cd[i,], fill="pink", col="darkred")+
   ggtitle(paste(c(cd$NAME[i],mo_ks_puma$GEOID10[intersect_matrix]),collapse = ", ")) -> map
   print(map)
}
```


```{r read-Neighborhoods}
file_name <- "Neighborhoods.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> Neighborhoods
head(Neighborhoods)
Neighborhoods                          %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("Neighborhoods")
Neighborhoods                          %>%
  st_transform(crs=st_crs(mo_ks_puma)) -> nbd
```

