---
title: "Tracts"
author: "Satya Golla"
date: "12/30/2021"
output: html_document
---

```{r setup}
library(sf)
library(tidyverse)
```


```{r read-tract-ks}
path_name <- "./data"
file_name <- "tl_2021_20_tract.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_tract_ks
head(all_tract_ks)
all_tract_ks                           %>%
     ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("ks-tract")
```


```{r read-tract-mo}
path_name <- "./data"
file_name <- "tl_2021_29_tract.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> all_tract_mo
head(all_tract_mo)
all_tract_mo                           %>%
     ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("mo-tract")
```



```{r combine-tracts}
all_tract_ks                %>%
  bind_rows(all_tract_mo)                %>%
 ggplot()                               +
      geom_sf(aes())                    +
      ggtitle("mo-ks-tracts")  
  
```


```{r read-Community-Districts}
file_name <- "Community_District.shp"
path_name                              %>%
  paste(file_name, sep="/")            %>%
  st_read(stringsAsFactors=FALSE)      -> Community_Districts
head(Community_Districts)
Community_Districts                  %>%
  ggplot()                              +
      geom_sf(aes())                    +
      ggtitle("Community_Districts")
Community_Districts %>%
  st_transform(crs=st_crs(mo_ks_tracts)) -> cd
```

```{r intersect-mo-ks-tracts-Community-Districts}
all_tracts                         %>%
  filter(STATEFP==20 | STATEFP==29)  ->       mo_ks_tracts
mo_ks_counties                       %>%
  st_intersects( cd, sparse=FALSE) -> intersect_matrix
 print(intersect_matrix)
 ggplot(data=cd, aes()) +
        geom_sf(fill="lightgreen", col="darkgreen") +
        geom_sf(data=cd[intersect_matrix, ], fill="pink", col="darkred") +
        ggtitle("mo-ks-tracts-Community-Districts")
```

variable in the file 

+ Variables:
  +   "STATEFP10"
  +   "PUMACE10"
  +   "GEOID10"
  +   "NAMELSAD10"
  +   "MTFCC10" 
  +   "FUNCSTAT10" 
  +   "ALAND10"
  +   "AWATER10"
  +   "INTPTLAT10"
  +   "INTPTLON10"
  +   "geometry"
  